# Generated by Django 4.2.7 on 2023-11-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
