# Generated by Django 4.2.7 on 2023-11-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_name_voter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='chosen_person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scope'),
        ),
    ]
