# Generated by Django 4.2.7 on 2023-11-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='chosen_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.scope'),
        ),
    ]
