# Generated by Django 4.2.7 on 2023-11-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scope_ischosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='chosen_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scope'),
        ),
    ]
