# Generated by Django 4.2.7 on 2023-11-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_person_alter_voter_chosen_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
